version: "3"
services:
  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    restart: always
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_EXPIRATION_HOURS=72h
      - JWT_USER_SECRET=ef3feesdfmfps
      - JWT_SUB_SECRET=wefdsf430f
      - NODEMAILER_EMAIL=
      - NODEMAILER_EMAIL_PASSWORD=
      - MONGO_URI=mongodb+srv://sovrakofanela:kLOA88IQNiC6tEQL@cluster0.x8lkq.mongodb.net/sovrakofanela?retryWrites=true&w=majority
      - MONGO_URI_PRODUCTION=mongodb+srv://sovrakofanela:kLOA88IQNiC6tEQL@cluster0.x8lkq.mongodb.net/sovrakofanela?retryWrites=true&w=majority
      - TWILLIO_ID=AC5825b4eca320382e450bb74ffa62cfe2
      - TWILLIO_TOKEN=51449689e928066286dcba9c9fb468ab
      - TWILLIO_NUMBER=19207728979
    ports:
      - "3001:3001"
    restart: always