services:
  server:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "5001:5001"
    volumes:
      - ./server:/usr/src/app/api
    links:
      - mongo
  client:
    container_name: admin
    restart: always
    build: ./client
    volumes:
      - ./admin:/usr/src/app/admin
    ports:
      - "3000:3000"
  mongo:
    hostname: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
