FROM node:12
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 3001
CMD ["npm", "start"]

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]